### ISSUE TITLE
Tag new release with openra version number

### ISSUE THREAD

**Issue by jjst** [rmoriz/openra-dockerfile#6]
Hey,

Any change you could tag the latest release with the version number (20200503) like the previous ones? https://hub.docker.com/r/rmoriz/openra/tags

I'm using your image in a docker-compose file to set up a dedicated server, this would allow me to easily pin in down to the openra version I want :)

Thanks :heart:

**Comment by rmoriz** [comment]
Fixed for x86/amd64

The arm build are broken for unknown reasons :-(

**Comment by jjst** [comment]
Thank you!
